#! /bin/bash
# FS QA Test 057
#
# Check if the filesystem will lockup when trying to allocate a new inode in an
# AG with no free inodes but with a corrupted agi->freecount showing free inodes
#
#-----------------------------------------------------------------------
# Copyright (c) 2017 Red Hat, Inc.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#-----------------------------------------------------------------------
#

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# remove previous $seqres.full before test
rm -f $seqres.full

# real QA test starts here

# Modify as appropriate.
_supported_fs xfs
_supported_os Linux
_require_scratch


_scratch_mkfs_xfs -mfinobt=0 >/dev/null 2>&1 \
	|| _notrun "Failed to initialize filesystem."

_scratch_mount >/dev/null 2>&1

# At the end of the filesystem initialization, AG 0 will still have 61 free
# inodes in the agi->freecount, create 61 extra dummy files to fill it up
for i in `seq 1 61`; do
	touch $SCRATCH_MNT/file$i
done

_scratch_unmount

# agi->freecount is 0 here, corrupt it showing extra free inodes
$XFS_DB_PROG -x -c "agi 0" -c "write freecount 10" $SCRATCH_DEV

_scratch_mount >/dev/null 2>&1

# Lock it up
touch $SCRATCH_MNT/foobar

# If we reach this point, the filesystem is fixed
echo "Silence is golden"
status=0
exit
